#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
  systemctl stop remote-prover.service >/dev/null 2>&1 || true
  systemctl disable remote-prover.service >/dev/null 2>&1 || true
  systemctl daemon-reload >/dev/null 2>&1 || true
fi

exit 0
